# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PnQgnOajI-BNFmCK3AwI22J7pMDlBbZY
"""

from datasets import load_dataset
from sklearn.model_selection import train_test_split
import random

def load_imdb_subset(size=3000):   # smaller for speed
    dataset = load_dataset("imdb")

    texts = dataset["train"]["text"]
    labels = dataset["train"]["label"]

    combined = list(zip(texts, labels))
    random.shuffle(combined)

    texts, labels = zip(*combined)

    texts = list(texts[:size])
    labels = list(labels[:size])

    return train_test_split(texts, labels, test_size=0.2, random_state=42)

X_train, X_test, y_train, y_test = load_imdb_subset()

# Load data
X_train, X_test, y_train, y_test = load_imdb_subset()

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score

# Naive Bayes
vec_nb = CountVectorizer(max_features=10000)
X_nb = vec_nb.fit_transform(X_train)
nb = MultinomialNB().fit(X_nb, y_train)

pred_nb = nb.predict(vec_nb.transform(X_test))

# Logistic Regression
vec_lr = TfidfVectorizer(max_features=10000)
X_lr = vec_lr.fit_transform(X_train)
lr = LogisticRegression(max_iter=1000).fit(X_lr, y_train)

pred_lr = lr.predict(vec_lr.transform(X_test))

def evaluate(name, y_true, y_pred):
    print(f"\n{name}")
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("F1:", f1_score(y_true, y_pred))

evaluate("Naive Bayes", y_test, pred_nb)
evaluate("Logistic Regression", y_test, pred_lr)

from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification, Trainer, TrainingArguments
import torch

tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

train_enc = tokenizer(X_train, truncation=True, padding=True)
test_enc = tokenizer(X_test, truncation=True, padding=True)

class Dataset(torch.utils.data.Dataset):
    def __init__(self, enc, labels):
        self.enc = enc
        self.labels = labels

    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.enc.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_ds = Dataset(train_enc, y_train)
test_ds = Dataset(test_enc, y_test)

model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=2)

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=1,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    logging_steps=50
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=test_ds
)

trainer.train()

preds = trainer.predict(test_ds).predictions.argmax(-1)

evaluate("DistilBERT", y_test, preds)

test_cases = [
    # ---- CATEGORY 1: ALL SHOULD PASS ----
    ("This is a good movie", 1),
    ("This is a bad movie", 0),
    ("Amazing acting and great story", 1),
    ("Terrible plot and boring film", 0),

    # ---- CATEGORY 2: NB vs LR behavior ----
    ("It was a long, long, long, long, long movie, but it was great.", 1),

    # ---- CATEGORY 3: neutral words takes as neg in nb and lr ----
    ("The cinematography was adequate, the sound was passable, and the acting was fine", 1),

    # ---- CATEGORY 4: STRUCTURE (BERT advantage) ----
    ("Bad start but excellent ending saves the film", 1),
    ("I expected this to be good, but it turned out to be great", 1),

    # ---- CATEGORY 5: HARD CASES (ALL FAIL) ----
    ("The prequel was terrible but this movie is actually good", 1),
    ("The actor's success streak broke with this film", 0),
    ("The story made up for the poor acting and weak plot", 1),
]

for text, label in test_cases:
    nb_pred = nb.predict(vec_nb.transform([text]))[0]
    lr_pred = lr.predict(vec_lr.transform([text]))[0]

    inputs = tokenizer([text], return_tensors="pt", truncation=True, padding=True).to(model.device)
    bert_pred = model(**inputs).logits.argmax(-1).item()

    print(f"\n{text}")
    print(f"True: {label} | NB: {nb_pred} | LR: {lr_pred} | BERT: {bert_pred}")
    